### ISSUE TITLE
check plugin_name.inc.php too in PluginInstaller

### ISSUE THREAD

**Issue by Takika** [roundcube/plugin-installer#15]
The PluginInstaller's install function (L60-64) copies config.inc.php.dist to config.inc.php if it doesn't exist.
But plugins can use plugin_name.inc.php file in any configured path so the installer have to check existence of these files too or to workaround it add a new command line parameter to disable this copy.

**Comment by alecpl** [comment]
Indeed, we should check all paths in use (see rcube_config::_construct()). rcube_config::resolve_paths() will be helpful.

**Comment by alecpl** [comment]
It is supposed to be fixed in plugin-installer 0.3.0.
