### ISSUE TITLE
plugin-installer is not installable

### ISSUE THREAD

**Issue by blade1989** [roundcube/plugin-installer#17]
I installed the `plugin-installer` via numerous ways, none actually install it. Last attempt was as follows:

     php composer.phar require "roundcube/plugin-installer *"

In the same matter I installed the calendar, tasks, filters, but the actual plugin-installer just wont install

 - Ubuntu 18.04.1
 - Roundcube 1.3.7

**Comment by thomascube** [comment]
Please be more specific. What was the error message composer showed you?
And why do you think the installer didn't install if you ware able to install plugnis? The latter wouldn't work if the former doesn't.

**Comment by blade1989** [comment]
I saw a screenshot that after installation the Plugin Manager is supposed to be available in RoundCube > Settings? 

After I executed the aforementioned command, I did not see it in settings?

**Comment by thomascube** [comment]
There is no plugin manager in Roundcube and nothings is displayed in settings.
Might be a third-party extension we're not aware of.
