### ISSUE TITLE
rcubeinitdb.sh - this file does not have an app associated with it for performing this action.

### ISSUE THREAD

**Issue by courtens** [roundcube/plugin-installer#21]
When installing plugins I see sometimes this window pop up, but have no idea what to do about it, or how to fix it. This time it was when calling `composer require dsoares/lastlogin`

![image](https://user-images.githubusercontent.com/27327453/65285655-f726cf00-daf1-11e9-93b9-ea9434a550e9.png)

I got this...
**Running database initialization script for lastlogin
The system cannot execute the specified program.**

**Comment by alecpl** [comment]
The only option will be to not execute any scripts, but do this in php. Should be quite simple since we have `rcmail_utils::db_init()` and `rcmail_utils::db_update()` since Roundcube 1.2.

**Comment by boscorelly** [comment]
It's not an issue ! you are trying to execute linx script on windows !

it's a human issue xD

**Comment by alecpl** [comment]
It shouldn't be an issue since plugin-installer 0.3.0. Closing.
