### ISSUE TITLE
plugins/skins installing to the wrong directory

### ISSUE THREAD

**Issue by MatthiasLohr** [roundcube/plugin-installer#41]
Hi,

I'm experiencing a really strange behavior and I have absolutely no idea where this is coming from. I suspect this issue to be connected with plugin installer, but maybe this might be the wrong place here. If so, sorry, however, maybe you can help me figuring out what is going wrong here.

What I would expect is the following (assuming a freshly downloaded and extraced release of roundcubemail):
  * `composer require johndoh/contextmenu:3.3` installs into `plugins`
  * `composer require roundcube/classic:1.6.0` installs into `skins`

What I'm experiencing is (again, freshly downloaded and extracted release of roundcubemail):
```bash
composer require roundcube/classic:1.6.0
composer require johndoh/contextmenu:3.3
```
Runs without errors, but both, the skin as well as the plugin, are installed into the `skins` directory:
```bash
$ ls skins
classic  contextmenu  elastic
```

Then, deleting the directory, creating a fresh directory with roundcube and reversing the order of composer require:
```bash
composer require johndoh/contextmenu:3.3
composer require roundcube/classic:1.6.0
```
Runs without errors, too, but both, the skin as well as the plugin, are now installed into the `plugins` directory:
```bash
$ ls skins
elastic
$ ls plugins
acl                         autologon    database_attachments  example_addressbook     http_authentication  krb_authentication  new_user_dialog    redundant_attachments    userinfo           zipdownload
additional_message_headers  autologout   debug_logger          filesystem_attachments  identicon            managesieve         new_user_identity  show_additional_headers  vcard_attachments
archive                     classic      emoticons             help                    identity_select      markasjunk          password           squirrelmail_usercopy    virtuser_file
attachment_reminder         contextmenu  enigma                hide_blockquote         jqueryui             newmail_notifier    reconnect          subscriptions_option     virtuser_query
```

So, it looks like that something is caching the first directory chosen for skin/plugin installation and keeps it for all subsequent installations.

Interestingly, this information is somehow cached within the roundcubemail directory. Deleting the directory and starting over "resets" the cache.

@thomascube, any idea?

Best regards
Matthias

**Comment by MatthiasLohr** [comment]
@thomascube, would you mind taking a look here? The problem still exists with the v1.6.3 image.

**Comment by buttercookie42** [comment]
I'm no PHP wizard, but the fact that the vendor directory [is set and cached in a static variable](https://github.com/roundcube/plugin-installer/blob/060acc66bb5f56d2005c88651ad888e49ec72767/src/Roundcube/Composer/ExtensionInstaller.php#L32) in the `ExtensionInstaller` class (that both `PluginInstaller` and `SkinInstaller` inherit from) looks a bit suspicious.

Some additional googling then found [this behaviour change in PHP 8.1](https://wiki.php.net/rfc/static_variable_inheritance), which looks like it could be related. If that is indeed the case, the RFC also includes [a proposed workaround](https://wiki.php.net/rfc/static_variable_inheritance#backward_incompatible_changes) for preserving the old behaviour, which the `ExtensionInstaller` presumably relies upon.
