### ISSUE TITLE
Installing a core plugin throws a composer warning

### ISSUE THREAD

**Issue by alecpl** [roundcube/plugin-installer#57]
On Roundcube master I wanted to test what happens if user would try to install a core plugin using composer.

So, I removed "roundcube/archive" from "require-dev" section, but left "repositories" intact. That way it will look like composer.json in a release package (where we remove the "require-dev" section).

```
./composer.sh require roundcube/archive
composer.json has been updated
Could not scan for classes inside "/home/alec/repos/roundcubemail/vendor/roundcube/archive/archive.php" which does not appear to be a file nor a folder
```

@mvorisek, Can we fix it so the warning is not printed? Or maybe it's a composer issue. Composer 2.7.2 on PHP 8.1.

**Comment by mvorisek** [comment]
https://github.com/roundcube/plugin-installer/blob/master/.github/workflows/ci.yml - please repro the issue using the CI

**Comment by mvorisek** [comment]
@alecpl is that still actual?

**Comment by alecpl** [comment]
I can't reproduce anymore.

**Comment by mvorisek** [comment]
Thank you for confirming!
