### ISSUE TITLE
Error refreshing the OAuth2 token

### ISSUE THREAD

**Issue by GieltjE** [roundcube/plugin-installer#8]
Syncing contacts for user <user>... Error refreshing the OAuth2 token, message: '{
  "error" : "invalid_grant"
}'

Can I help debug this?

**Comment by thomascube** [comment]
I don't think this is related to the plugin installer (it does not sync contacts or somesuch). Could a failure of a plugin you have installed. Please contact the author(s) of any plugins you're using which deal with contacts.
